# netlify.toml (at repo root)
[build]
  publish = "TNKLCP"   # this is your site folder

# pretty URL helpers
[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 301

[[redirects]]
  from = "/employee"
  to = "/employee.html"
  status = 301

[[redirects]]
  from = "/customer"
  to = "/customer.html"
  status = 301
